layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  #sort_by: stars
    #- pushed
  limit: 20
  include:
    - name: now-deployment
      full_name: amondnet/now-deployment
    - name: openapi-generator
      full_name:  OpenAPITools/openapi-generator
    - name: flutter_kakao_login
      full_name: JosephNK/flutter_kakao_login
    - name: mockk
      full_name: mockk/mockk
    - name: maxwell
      full_name: zendesk/maxwell
  exclude:
    archived: false
    forks: false
    projects:
      - now-deployment
      - openapi-generator
      - flutter_kakao_login
      - mockk
      - test-a
      - amondnet.github.io
      - dart-json-mapper
      - kiwi
      - firestore_ui
      - pusher-websocket-swift
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: 민수-이-301a8b82
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://amond.net
  # youtube: your_username

topics:
  - name: Flutter
    web_url: https://github.com/topics/flutter
    image_url: https://raw.githubusercontent.com/github/explore/cebd63002168a05a6a642f309227eefeccd92950/topics/flutter/flutter.png

  - name: Kotlin
    web_url: https://github.com/topics/kotlin
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kotlin/kotlin.png

  - name: Spring Boot
    web_url: https://github.com/topics/spring-boot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png

